- Python is a general purpose language with everyone from socket programming, to web servers, to databases
- To *activate* these various capabilities, you have to import the correct packages
    - By *activate*, I mean import the functions and objects that support these capabilities into our namespace
- We will use the following packages in this class
    - numpy
    - scipy
    - matplotlib
    - pyamg
- The package import syntax is simple



In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import scipy.linalg as sla
%matplotlib inline

First, we explore the SVD capabilities in Python

In [3]:
n = 4
A = sp.rand(n,n)
print(A)

[[0.60262333 0.06784845 0.59628614 0.9550051 ]
 [0.15559498 0.50413713 0.34912482 0.57894737]
 [0.84068149 0.38197826 0.89981552 0.91587882]
 [0.12368394 0.77442551 0.21909403 0.13940927]]


In [4]:
# Generate SVD from Scipy Linalg sub-package 
[U,S,Vh] = sla.svd(A)

In [5]:
# Print out the SVD
np.set_printoptions(precision=2, suppress=True)
print(U)
print('------')
print(S)
print('------')
print(Vh)

[[-0.56  0.41  0.39  0.61]
 [-0.36 -0.36  0.69 -0.52]
 [-0.71  0.12 -0.58 -0.37]
 [-0.23 -0.83 -0.19  0.48]]
------
[2.2  0.8  0.29 0.06]
------
[[-0.46 -0.3  -0.52 -0.65]
 [ 0.24 -0.94  0.06  0.22]
 [-0.61 -0.01 -0.34  0.72]
 [ 0.6   0.14 -0.78  0.14]]


In [6]:
# Verify the SVD is correct
# ==> Note how we do matrix-matrix products!  USE DOT()!
print(A - np.dot(U, np.dot(np.diag(S),Vh)) )

[[ 0. -0.  0.  0.]
 [-0.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [-0.  0.  0. -0.]]


In [7]:
# Be careful...svd returns the adjoint of V !
print(A - np.dot(U, np.dot(np.diag(S),Vh.T)) )

[[ 0.21  0.66 -0.14  1.73]
 [-0.21  0.41 -0.04  1.24]
 [ 0.04  0.86 -0.1   1.71]
 [-0.32  0.27 -0.13  0.48]]


__Can solve a linear system with SVD__
\begin{align}
    A &= U \Sigma V^* \quad \Rightarrow \\
    A^{-1} &= V \Sigma^{-1} U^*
\end{align}
    

In [8]:
b = sp.rand(n,1)
x = np.dot(U.T, b)
x = x/S.reshape(-1,1)
x = np.dot(Vh.T,x)
print(np.dot(A,x))
print("----")
print(b)

[[0.66]
 [0.01]
 [0.82]
 [0.63]]
----
[[0.66]
 [0.01]
 [0.82]
 [0.63]]


__If you are not familiar with Python and Scipy/Numpy then please do some of tutorial(s) for these technologies.__
    - See scipy_tutorial.pdf in the lecture materials
    - The course webpage has some links at the bottom, but the web is filled many resources here, too.